### PR TITLE
Use clang for tests as well

### PR DESCRIPTION
**Pull request by javierhonduco**
Compile tests using clang and gcc. This would be useful to detect possible, albeit unlikely code that breaks under clang.

As per [the docs](https://docs.travis-ci.com/user/languages/c/) this should set `CC` env variable accordingly

### CODE REVIEW

**Comment by javierhonduco** [comment]
Ops, did not notice the Makefile hardcodes the compiler. 

Would you be ok with me removing the hardcoded GCC or prefer to be explicit about the compiler in the travis.yml file?

**Comment by mmarchini** [comment]
> Would you be ok with me removing the hardcoded GCC or prefer to be explicit about the compiler in the travis.yml file?

Yes, it should be fine. 

In the future I want to move from make to cmake, but right now I don't have the bandwidth do to that.

**Comment by javierhonduco** [comment]
Sorry, haven't had the time to get to this, will update the PR next week 😄 

> In the future I want to move from make to cmake, but right now I don't have the bandwidth do to that.

I'm personally happy with make in this case but I guess you're thinking on this to require the right `libelf`?

**Comment by dalehamel** [comment]
@javierhonduco heads-up, recent changes to #24 might conflict, as it moves to using a matrix to test for both trusty and bionic.

**Comment by javierhonduco** [comment]
Thanks! Will wait for your changes to be merged 😄

**Comment by mmarchini** [comment]
Hi! I forked the project, it's now located at https://github.com/linux-usdt/libstapsdt and I'll be continuing development there. I moved our CI from Travis to GitHub Actions and added both gcc and clang to the matrix.

**Comment by javierhonduco** [comment]
Thanks, mary! Would you mind perhaps mentioning that it's a fork of this repo (and archive this one, if possible) to avoid confusion? Cheers

**Pull request closed without merging**
